### ISSUE TITLE
Notice: Undefined index: image

### ISSUE THREAD

**Issue by necony286** [Mo45/Rust-Server-Website-Template#10]
## Actual behavior
Notice: Undefined index: image in Rust-Server-Website-Template-master\includes.php on line 32
## Steps to reproduce the problem
localhost with xampp 

edit: after switching to the RUST-SERVERS.INFO API the message was gone.

**Comment by Mo45** [comment]
Rust-Servers.net **don't** provide server image in their API. This **Notice**, not error. But if you want to keep your log clean, [check this](https://github.com/Mo45/Rust-Server-Website-Template/commit/6032a04ec4a4b22eaa3b4b30ddd810adb2d150bd#diff-90696b34b937136cdebf9c08aeb14d23).

**Comment by necony286** [comment]
thanks :) i figured it when i did get request for postman.
so i just edit line 16?
"		
if(MODULE_SERVERS_V2 == "ON"){$s1_img = "img/serverlogo.png";};//Remove PHP Notice in logs
"
ON to OFF?

**Comment by Mo45** [comment]
> thanks :) i figured it when i did get request for postman.
> so i just edit line 16?
> "
> if(MODULE_SERVERS_V2 == "ON"){$s1_img = "img/serverlogo.png";};//Remove PHP Notice in logs
> "
> ON to OFF?

I strongly reccomend you to use **rust-servers.net** API (more stable & faster). If you will use **rust-servers.info** API you don't need to change anything. Otherwise:

Add `if(MODULE_SERVERS_V2 == "ON"){$s1_img = "img/serverlogo.png";};//Remove PHP Notice in logs
if(MODULE_SERVERS_V2 == "OFF"){`
before `$s1_img		= $parsed_json['image'];`
and then close **IF** by adding `};` before `$s1_ip		= $parsed_json['address'];`

Or just download updated [includes.php](https://github.com/Mo45/Rust-Server-Website-Template/raw/master/includes.php).

**Comment by necony286** [comment]
thx
